### ISSUE TITLE
Issue while running command migrate generate.

### ISSUE THREAD

**Issue by jay-bhatt-jb** [sensedeep/onetable-cli#4]
NPM command:  "onetable migrate generate"
TypeError: config.onetable.config is not iterable
    at CLI.getConfig (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:504:42)
    at async CLI.init (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:102:22)
    at async main (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:605:9)
config.onetable.config is not iterable

1. migrate.json - file >> 
```
{
    "name": "Users",
    "schema": "schema-onetable.js",
    "profiles": {
        "dev": {
            "endpoint": "http://localhost:8000"
        }
    }
}
```
OR
2. migrate.json - file >> 
```
{
  name: 'test',
   schema: './schema.js',
    aws: {
        endpoint: 'http://localhost:8000'
    }
}
```
Tried various changes in the migrate.json file but no luck still getting the same error.
Can anyone help with the solution for this particular issue?

**Comment by mobsense** [comment]
There was a bug AND you need to use:

```
onetable generation migration
```

**Comment by jay-bhatt-jb** [comment]
Not working in the latest build(@1.0.4) as well, using the command suggested. 

NPM command: "onetable generation migration"
TypeError: config.onetable.config is not iterable
    at CLI.getConfig (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:511:42)
    at async CLI.init (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:102:22)
    at async main (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:612:9)
config.onetable.config is not iterable

**Comment by mobsense** [comment]
Sorry, my mistype: (generate) not generation

    onetable generate migration

**Comment by jay-bhatt-jb** [comment]
Getting the same error, with new command as well.

**Comment by mobsense** [comment]
Are you using 1.0.4?

**Comment by jay-bhatt-jb** [comment]
Yes. Created a new project and installed the latest version.

**Comment by mobsense** [comment]
Can you add to your migrate.json

    config: []

**Comment by mobsense** [comment]
Thanks for reporting. We can reproduce.

We've fixed that issue (and an associated one) and clarified the documentation. See version 1.0.5

The config: [] is an undocumented feature where you can supply additional JSON configuration files to blend with the migration.json file.

**Comment by jay-bhatt-jb** [comment]
Getting new error while reading schema after fixing config issue : 

PS D:\RS_Connect\Test_Folder> onetable generate migration
Error: 
Cannot load schema D:\RS_Connect\Test_Folder\schema.js Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:756:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at Loader.import (internal/modules/esm/loader.js:181:28)
    at importModuleDynamically (internal/modules/esm/translators.js:109:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:32:14)
    at CLI.readSchema (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:155:26)
    at CLI.init (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:120:33)
    at async main (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:612:9) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

**Comment by mobsense** [comment]
Do you have a package.json on that directory?

If so, try without it. Also check if any parent directories have package.json.

Try in a bare directory without a package.json.  We've just been independently made aware of that issue and are investigating. Seems to be fine without a package.json.

**Comment by jay-bhatt-jb** [comment]
Tried creating a sub-folder and adding schema.js, in that folder but still getting same error.

**Comment by mobsense** [comment]
Okay. You must also have no package.json files in any parent directory. Node chases up the tree looking for them. Ugh!.

A cleaner alternative should be try renaming the schema.js to schema.mjs and define that in your migrate.json. I just tested that and it seems to work for me here.

**Comment by jay-bhatt-jb** [comment]
Trying in windows pc, are you using windows?  Because creating a .mjs file is also not helping. And package.json will be required are we using in node.js project. So any other approach we can try?

**Comment by mobsense** [comment]
What message did you get for .mjs?  

No, I'm not testing on Windows, but this is an issue on non-windows too.

**Comment by mobsense** [comment]
Another option: You can create a package.json in your migrations directory and put a

    type: "module"

in the package.json.

**Comment by jay-bhatt-jb** [comment]
Getting below error with mjs file >
Cannot load schema D:\RS_Connect\Test_Folder\schema.mjs Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:756:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at Loader.import (internal/modules/esm/loader.js:181:28)
    at importModuleDynamically (internal/modules/esm/translators.js:109:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:32:14)
    at CLI.readSchema (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:155:26)
    at CLI.init (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:120:33)
    at async main (file:///C:/Users/jay.bhatt/AppData/Roaming/npm/node_modules/onetable-cli/dist/cli.js:612:9) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

**Comment by mobsense** [comment]
Can you please post your migrate.json and a listing of your migrations directory.

**Comment by jay-bhatt-jb** [comment]
Migrate.json : 
{
    name: 'test',
    config: [],
     schema: './migrations/schema.mjs',
      aws: {
          endpoint: 'http://localhost:8000'
    }
}
Schema.mjs: 
export default {
    indexes: { },
    models: {
        Users: {
            id: { type: Number },
            Name: { type: String }
        }
    }
}


![image](https://user-images.githubusercontent.com/83215230/116857942-3e0bfe80-ac1b-11eb-9c76-6b0d1984d9e6.png)

**Comment by mobsense** [comment]
Thanks. And did you install 1.0.5?

**Comment by jay-bhatt-jb** [comment]
Yes. Added new version and trying in same.

**Comment by mobsense** [comment]
You will also need to define indexes and User PK/SK

For example. I'm not sure what your real PK/SK names and what you want them to be in your Users table. But here is a hint:

```
export default {
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
    },
    models: {
        Users: {
            pk: { type: String, value: 'user:${Name}' },
            sk: { type: String, value: 'user:' },
            id: { type: Number },
            Name: { type: String }
        }
    }
}
```

**Comment by mobsense** [comment]
It is working here. We'll dust off a windows system and try that. I need to run, but will get back to this early tomorrow.

Thanks for reporting and giving us feedback to fix.

**Comment by jay-bhatt-jb** [comment]
Added a similar schema earlier and also tried with this now also but it's not touching the schema file. I think it's not reading the schema file else it should give some operational error. Right?

**Comment by mobsense** [comment]
Got a solution:  Windows requires 'file:///' to be prefixed to the schema by the cli. We now do this internally.

Version 1.0.6

**Comment by jay-bhatt-jb** [comment]
Great, it worked. But getting some error in query key condition. Any idea on this error? Tried using the schema shared by you. Then also same error is coming. Any modification in the schema is required?

ValidationException: Query key condition not supported
    at Request.extractError (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\protocol\json.js:52:27)    
    at Request.callListeners (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)      
    at Request.emit (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'ValidationException',
  time: 2021-05-03T12:04:19.405Z,
  requestId: '3e54056f-3a55-4f64-b93f-a23aeeaea84c',
  statusCode: 400,
  retryable: false,
  retryDelay: 47.415306870417
}
Query key condition not supported

**Comment by mobsense** [comment]
Great, glad that worked.

If you add {log: true} to the API params, you can see the actual generated query.

Also, when posting issues, please include the actual query and log results. Otherwise, we are just guessing what you are testing and what is the generated query.

E.g.

```
    let users = await User.find({id: NNN}, {log: true})
```

**Comment by jay-bhatt-jb** [comment]
Schema.js 
export default {
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
    },
    models: {
        Users: {
            pk: { type: String, value: 'Users:${Name}' },
            sk: { type: String, value: 'Users:' },
            id: { type: String },
            Name: { type: String },
        }
    }
}
Migrate.json 
{
    name: 'Users',
     schema: './migrations/schema.mjs',
      aws: {
        endpoint: "http://localhost:8000"
    }
}

Command: onetable generate migration
Error while running above command : 

ValidationException: Query key condition not supported
    at Request.extractError (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\protocol\json.js:52:27)    
    at Request.callListeners (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)      
    at Request.emit (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\jay.bhatt\AppData\Roaming\npm\node_modules\onetable-cli\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'ValidationException',
  time: 2021-05-04T06:29:01.457Z,
  requestId: '8847e5ae-556a-43f6-ab9b-6b763e5829df',
  statusCode: 400,
  retryable: false,
  retryDelay: 36.947629882915244
}
Query key condition not supported

Looks like schema.mjs has some issue but not identifying. can you help with the same?

**Comment by mobsense** [comment]
Can you post the actual API code and use {log: true} and post the underlying command sent to DynamoDB?

**Comment by jay-bhatt-jb** [comment]
Not calling API yet. While updating the schema at the time of migration generate its showing this particular error.

**Comment by mobsense** [comment]
Does the table exist in the local db?

Can you post your table setup params?

**Comment by jay-bhatt-jb** [comment]
Yes, a table exists created manually in the local DB
Params: 
var params = {
    TableName: 'Users',
    KeySchema: [
        { AttributeName: "id", KeyType: "HASH"},  //Partition key
    ],
    AttributeDefinitions: [
        { AttributeName: "id", AttributeType: "N" },
   ],
    ProvisionedThroughput: {
        ReadCapacityUnits: 5,
        WriteCapacityUnits: 5
    }
};
dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err); // an error occurred
    else ppJson(data); // successful response
});

**Comment by mobsense** [comment]
Thanks. FYI: use 3 backticks to format your code in posts 

```
code here
```

**Comment by mobsense** [comment]
Your hash key should be "pk" and your sort key should be "sk" to match your schema.

Best practices are not to use actual attributes as your hash/sort keys. So your key schema should NOT be "id".

**Comment by jay-bhatt-jb** [comment]
Did not get the point you are asking to change. Can you suggest what changes should I make in the schema.mjs to work?

> Schema.mjs

```
export default {
    indexes: {
        primary: { hash: 'pk', sort: 'sk' },
    },
    models: {
        Users: {
            pk: { type: String, value: 'Users:${Name}' },
            sk: { type: String, value: 'Users:' },
            id: { type: String },
            Name: { type: String },
        }
    }
}
```

**Comment by mobsense** [comment]
```
var params = {
    TableName: 'Users',
    KeySchema: [
        { AttributeName: "pk", KeyType: "HASH"},
        { AttributeName: "sk", KeyType: "RANGE"},
    ],
    ProvisionedThroughput: {
        ReadCapacityUnits: 5,
        WriteCapacityUnits: 5
    }
};
```

**Comment by mobsense** [comment]
The pk, sk are the names of the keys. These are overloaded. i.e. you store different values in these depending on the entity model. 

Your "id" and "Name" are attribute names. They will vary by model. The pk is constructed at runtime via the value template "Users:${Name}". The sort key will always be "Users:".  This becomes useful as your store more entities in the single-table.

Note:

- Your table then should not be called Users, but something more generic as you store multiple entities in a single table
- Be consistent with case and plurals. Don't use "id" and "Name".  Decide if your entity names will be singular User vs plural Users.
